image: node:8.12.0 

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install singlemd -g
  - singlemd --input ./README.md --output index.html --style ./style.css --title singlemd
  - mkdir ./public && mv index.html ./public
  artifacts:
    paths:
    - public
  only:
    - master